# CLOSE ISSUE BOT
# ---------------
# A bot which helps you to close issues that don't include some specific contents.
# See how to use it in https://github.com/offu/close-issue-app.

# Comment that will be sent if an issue is judged to be closed.
comment: >-
  This issue has been automatically closed because the PROBLEM REPORT TEMPLATE is missing or incomplete.
  
  Filling the template is required so standard questions don't need to be asked again each time.
  Our ability to provide assistance is greatly hampered if few minutes are not taken to complete the issue template
  with the requested information. The details requested potentially affect which options to pursue. The small amount
  of time you will spend completing the template will also help the volunteers, providing assistance to you, to reduce
  the time required to help you.
  
  Please, could you be so kind on completing the [PROBLEM REPORT TEMPLATE](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

  Thank you for taking the time to report, hopefully it can be resolved soon.
  
  [Docs](https://tasmota.github.io/docs/) for more information.
  
  [Discussions](https://github.com/arendst/Tasmota/discussions) for Questions, Feature Requests and Projects.
  
  [Chat](https://discord.gg/Ks2Kzd4) for more users experience.  
 
  Please check the [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md) and the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

issueConfigs:
# There can be several configs for different kind of issues.
- content:
# template 1: bug report
  - "PROBLEM DESCRIPTION"
  - "REQUESTED INFORMATION"
  - "TO REPRODUCE"
  - "EXPECTED BEHAVIOUR" 
- content:
# template 2: feature request
  - "Have you looked for this feature in other issues and in the docs"
  - "Describe the solution you'd like"
  
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: true
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "template missing/incomplete"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
